/* This file was automatically generated. Do not edit by hand. */

const {
  ns1,
  rdfs,
  sh,
  rdf,
  xsd
} = {
  'ns1': 'http://localhost/',
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'sh': 'http://www.w3.org/ns/shacl#',
  'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'xsd': 'http://www.w3.org/2001/XMLSchema#'
}

export default ({ blankNode, literal, namedNode, quad }: import('rdf-js').DataFactory): import('rdf-js').Quad[] => {
  const blankNodes: import('rdf-js').BlankNode[] = []
  for (let i = 0; i < 28; i++) {
    blankNodes.push(blankNode())
  }

  return [
    quad(
      namedNode(`${ns1}app`),
      namedNode(`${rdfs}label`),
      literal(`XRM Entities`, 'en')
    ),
    quad(
      namedNode(`${ns1}app`),
      namedNode(`${rdfs}comment`),
      literal(`This graph describes the XRM Entities`, 'en')
    ),
    quad(
      blankNodes[0],
      namedNode(`${sh}prefix`),
      literal(`sh`)
    ),
    quad(
      blankNodes[0],
      namedNode(`${sh}namespace`),
      literal(`http://www.w3.org/ns/shacl#`)
    ),
    quad(
      namedNode(`${ns1}app`),
      namedNode(`${sh}declare`),
      blankNodes[0]
    ),
    quad(
      blankNodes[1],
      namedNode(`${sh}prefix`),
      literal(`xsd`)
    ),
    quad(
      blankNodes[1],
      namedNode(`${sh}namespace`),
      literal(`http://www.w3.org/2001/XMLSchema#`)
    ),
    quad(
      namedNode(`${ns1}app`),
      namedNode(`${sh}declare`),
      blankNodes[1]
    ),
    quad(
      blankNodes[2],
      namedNode(`${sh}prefix`),
      literal(`xrm`)
    ),
    quad(
      blankNodes[2],
      namedNode(`${sh}namespace`),
      literal(`http://localhost/`)
    ),
    quad(
      namedNode(`${ns1}app`),
      namedNode(`${sh}declare`),
      blankNodes[2]
    ),
    quad(
      blankNodes[3],
      namedNode(`${sh}prefix`),
      literal(`app`)
    ),
    quad(
      blankNodes[3],
      namedNode(`${sh}namespace`),
      literal(`http://localhost/app`)
    ),
    quad(
      namedNode(`${ns1}app`),
      namedNode(`${sh}declare`),
      blankNodes[3]
    ),
    quad(
      blankNodes[4],
      namedNode(`${sh}prefix`),
      literal(`rdf`)
    ),
    quad(
      blankNodes[4],
      namedNode(`${sh}namespace`),
      literal(`http://www.w3.org/1999/02/22-rdf-syntax-ns#`)
    ),
    quad(
      namedNode(`${ns1}app`),
      namedNode(`${sh}declare`),
      blankNodes[4]
    ),
    quad(
      blankNodes[5],
      namedNode(`${sh}prefix`),
      literal(`rdfs`)
    ),
    quad(
      blankNodes[5],
      namedNode(`${sh}namespace`),
      literal(`http://www.w3.org/2000/01/rdf-schema#`)
    ),
    quad(
      namedNode(`${ns1}app`),
      namedNode(`${sh}declare`),
      blankNodes[5]
    ),
    quad(
      namedNode(`${ns1}app`),
      namedNode(`${sh}suggestedShapesGraph`),
      namedNode(`${ns1}app`)
    ),
    quad(
      namedNode(`${ns1}XrmProjectShape`),
      namedNode(`${rdf}type`),
      namedNode(`${sh}NodeShape`)
    ),
    quad(
      namedNode(`${ns1}XrmProjectShape`),
      namedNode(`${sh}targetClass`),
      namedNode(`${ns1}Project`)
    ),
    quad(
      blankNodes[6],
      namedNode(`${sh}name`),
      literal(`xrmId`)
    ),
    quad(
      blankNodes[6],
      namedNode(`${sh}path`),
      namedNode(`${ns1}id`)
    ),
    quad(
      blankNodes[6],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      namedNode(`${ns1}XrmProjectShape`),
      namedNode(`${sh}property`),
      blankNodes[6]
    ),
    quad(
      blankNodes[7],
      namedNode(`${sh}name`),
      literal(`mapping`)
    ),
    quad(
      blankNodes[7],
      namedNode(`${sh}path`),
      namedNode(`${ns1}mapping`)
    ),
    quad(
      blankNodes[7],
      namedNode(`${sh}class`),
      namedNode(`${ns1}XrmMapping`)
    ),
    quad(
      namedNode(`${ns1}XrmProjectShape`),
      namedNode(`${sh}property`),
      blankNodes[7]
    ),
    quad(
      blankNodes[8],
      namedNode(`${sh}name`),
      literal(`dataSource`)
    ),
    quad(
      blankNodes[8],
      namedNode(`${sh}path`),
      namedNode(`${ns1}dataSource`)
    ),
    quad(
      blankNodes[8],
      namedNode(`${sh}class`),
      namedNode(`${ns1}XrmDataSource`)
    ),
    quad(
      namedNode(`${ns1}XrmProjectShape`),
      namedNode(`${sh}property`),
      blankNodes[8]
    ),
    quad(
      blankNodes[9],
      namedNode(`${sh}name`),
      literal(`hasVocabularySource`)
    ),
    quad(
      blankNodes[9],
      namedNode(`${sh}path`),
      namedNode(`${ns1}hasVocabularySource`)
    ),
    quad(
      blankNodes[9],
      namedNode(`${sh}class`),
      namedNode(`${ns1}XrmVocabularySource`)
    ),
    quad(
      namedNode(`${ns1}XrmProjectShape`),
      namedNode(`${sh}property`),
      blankNodes[9]
    ),
    quad(
      namedNode(`${ns1}XRMDataSourceShape`),
      namedNode(`${rdf}type`),
      namedNode(`${sh}NodeShape`)
    ),
    quad(
      namedNode(`${ns1}XRMDataSourceShape`),
      namedNode(`${sh}targetClass`),
      namedNode(`${ns1}XrmDataSource`)
    ),
    quad(
      blankNodes[10],
      namedNode(`${sh}path`),
      namedNode(`${ns1}id`)
    ),
    quad(
      blankNodes[10],
      namedNode(`${sh}name`),
      literal(`xrmId`)
    ),
    quad(
      blankNodes[10],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[10],
      namedNode(`${sh}minCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      blankNodes[10],
      namedNode(`${sh}maxCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMDataSourceShape`),
      namedNode(`${sh}property`),
      blankNodes[10]
    ),
    quad(
      blankNodes[11],
      namedNode(`${sh}path`),
      namedNode(`${ns1}fileName`)
    ),
    quad(
      blankNodes[11],
      namedNode(`${sh}name`),
      literal(`fileName`)
    ),
    quad(
      blankNodes[11],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[11],
      namedNode(`${sh}minCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      blankNodes[11],
      namedNode(`${sh}maxCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMDataSourceShape`),
      namedNode(`${sh}property`),
      blankNodes[11]
    ),
    quad(
      blankNodes[12],
      namedNode(`${sh}path`),
      namedNode(`${ns1}field`)
    ),
    quad(
      blankNodes[12],
      namedNode(`${sh}name`),
      literal(`field`)
    ),
    quad(
      blankNodes[12],
      namedNode(`${sh}class`),
      namedNode(`${ns1}XRMDataSourceField`)
    ),
    quad(
      namedNode(`${ns1}XRMDataSourceShape`),
      namedNode(`${sh}property`),
      blankNodes[12]
    ),
    quad(
      namedNode(`${ns1}XRMDataSourceFieldShape`),
      namedNode(`${rdf}type`),
      namedNode(`${sh}NodeShape`)
    ),
    quad(
      namedNode(`${ns1}XRMDataSourceFieldShape`),
      namedNode(`${sh}targetClass`),
      namedNode(`${ns1}XRMDataSourceField`)
    ),
    quad(
      blankNodes[13],
      namedNode(`${sh}path`),
      namedNode(`${ns1}variable`)
    ),
    quad(
      blankNodes[13],
      namedNode(`${sh}name`),
      literal(`variable`)
    ),
    quad(
      blankNodes[13],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[13],
      namedNode(`${sh}minCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      blankNodes[13],
      namedNode(`${sh}maxCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMDataSourceFieldShape`),
      namedNode(`${sh}property`),
      blankNodes[13]
    ),
    quad(
      blankNodes[14],
      namedNode(`${sh}path`),
      namedNode(`${ns1}fileName`)
    ),
    quad(
      blankNodes[14],
      namedNode(`${sh}name`),
      literal(`fieldName`)
    ),
    quad(
      blankNodes[14],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[14],
      namedNode(`${sh}minCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      blankNodes[14],
      namedNode(`${sh}maxCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMDataSourceFieldShape`),
      namedNode(`${sh}property`),
      blankNodes[14]
    ),
    quad(
      blankNodes[15],
      namedNode(`${sh}path`),
      namedNode(`${ns1}sample`)
    ),
    quad(
      blankNodes[15],
      namedNode(`${sh}name`),
      literal(`sample`)
    ),
    quad(
      blankNodes[15],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[15],
      namedNode(`${sh}minCount`),
      literal(`0`, namedNode(`${xsd}integer`))
    ),
    quad(
      blankNodes[15],
      namedNode(`${sh}maxCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMDataSourceFieldShape`),
      namedNode(`${sh}property`),
      blankNodes[15]
    ),
    quad(
      namedNode(`${ns1}XRMVocabularySourceShape`),
      namedNode(`${rdf}type`),
      namedNode(`${sh}NodeShape`)
    ),
    quad(
      namedNode(`${ns1}XRMVocabularySourceShape`),
      namedNode(`${sh}targetClass`),
      namedNode(`${ns1}XrmVocabularySource`)
    ),
    quad(
      blankNodes[16],
      namedNode(`${sh}path`),
      namedNode(`${ns1}id`)
    ),
    quad(
      blankNodes[16],
      namedNode(`${sh}name`),
      literal(`xrmId`)
    ),
    quad(
      blankNodes[16],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[16],
      namedNode(`${sh}minCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      blankNodes[16],
      namedNode(`${sh}maxCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMVocabularySourceShape`),
      namedNode(`${sh}property`),
      blankNodes[16]
    ),
    quad(
      blankNodes[17],
      namedNode(`${sh}path`),
      namedNode(`${ns1}namespace`)
    ),
    quad(
      blankNodes[17],
      namedNode(`${sh}name`),
      literal(`namespace`)
    ),
    quad(
      blankNodes[17],
      namedNode(`${sh}class`),
      namedNode(`${ns1}XrmNamespace`)
    ),
    quad(
      blankNodes[17],
      namedNode(`${sh}minCount`),
      literal(`0`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMVocabularySourceShape`),
      namedNode(`${sh}property`),
      blankNodes[17]
    ),
    quad(
      namedNode(`${ns1}XRMNamespaceShape`),
      namedNode(`${rdf}type`),
      namedNode(`${sh}NodeShape`)
    ),
    quad(
      namedNode(`${ns1}XRMNamespaceShape`),
      namedNode(`${sh}targetClass`),
      namedNode(`${ns1}XrmNamespace`)
    ),
    quad(
      blankNodes[18],
      namedNode(`${sh}path`),
      namedNode(`${ns1}name`)
    ),
    quad(
      blankNodes[18],
      namedNode(`${sh}name`),
      literal(`name`)
    ),
    quad(
      blankNodes[18],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[18],
      namedNode(`${sh}minCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      blankNodes[18],
      namedNode(`${sh}maxCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMNamespaceShape`),
      namedNode(`${sh}property`),
      blankNodes[18]
    ),
    quad(
      blankNodes[19],
      namedNode(`${sh}path`),
      namedNode(`${ns1}class`)
    ),
    quad(
      blankNodes[19],
      namedNode(`${sh}name`),
      literal(`class`)
    ),
    quad(
      blankNodes[19],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[19],
      namedNode(`${sh}minCount`),
      literal(`0`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMNamespaceShape`),
      namedNode(`${sh}property`),
      blankNodes[19]
    ),
    quad(
      blankNodes[20],
      namedNode(`${sh}path`),
      namedNode(`${ns1}property`)
    ),
    quad(
      blankNodes[20],
      namedNode(`${sh}name`),
      literal(`property`)
    ),
    quad(
      blankNodes[20],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[20],
      namedNode(`${sh}minCount`),
      literal(`0`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMNamespaceShape`),
      namedNode(`${sh}property`),
      blankNodes[20]
    ),
    quad(
      blankNodes[21],
      namedNode(`${sh}path`),
      namedNode(`${ns1}datatype`)
    ),
    quad(
      blankNodes[21],
      namedNode(`${sh}name`),
      literal(`datatype`)
    ),
    quad(
      blankNodes[21],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[21],
      namedNode(`${sh}minCount`),
      literal(`0`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMNamespaceShape`),
      namedNode(`${sh}property`),
      blankNodes[21]
    ),
    quad(
      namedNode(`${ns1}XRMMappingShape`),
      namedNode(`${rdf}type`),
      namedNode(`${sh}NodeShape`)
    ),
    quad(
      namedNode(`${ns1}XRMMappingShape`),
      namedNode(`${sh}targetClass`),
      namedNode(`${ns1}XrmMapping`)
    ),
    quad(
      blankNodes[22],
      namedNode(`${sh}path`),
      namedNode(`${ns1}name`)
    ),
    quad(
      blankNodes[22],
      namedNode(`${sh}name`),
      literal(`name`)
    ),
    quad(
      blankNodes[22],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[22],
      namedNode(`${sh}minCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      blankNodes[22],
      namedNode(`${sh}maxCount`),
      literal(`1`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMMappingShape`),
      namedNode(`${sh}property`),
      blankNodes[22]
    ),
    quad(
      blankNodes[23],
      namedNode(`${sh}path`),
      namedNode(`${ns1}description`)
    ),
    quad(
      blankNodes[23],
      namedNode(`${sh}name`),
      literal(`description`)
    ),
    quad(
      blankNodes[23],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[23],
      namedNode(`${sh}minCount`),
      literal(`0`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMMappingShape`),
      namedNode(`${sh}property`),
      blankNodes[23]
    ),
    quad(
      blankNodes[24],
      namedNode(`${sh}path`),
      namedNode(`${sh}property`)
    ),
    quad(
      blankNodes[24],
      namedNode(`${sh}name`),
      literal(`property`)
    ),
    quad(
      blankNodes[24],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[24],
      namedNode(`${sh}minCount`),
      literal(`0`, namedNode(`${xsd}integer`))
    ),
    quad(
      blankNodes[24],
      namedNode(`${sh}class`),
      namedNode(`${ns1}XrmPropertyMapping`)
    ),
    quad(
      namedNode(`${ns1}XRMMappingShape`),
      namedNode(`${sh}property`),
      blankNodes[24]
    ),
    quad(
      namedNode(`${ns1}XRMMappingPropertyShape`),
      namedNode(`${rdf}type`),
      namedNode(`${sh}NodeShape`)
    ),
    quad(
      namedNode(`${ns1}XRMMappingPropertyShape`),
      namedNode(`${sh}targetClass`),
      namedNode(`${ns1}XrmPropertyMapping`)
    ),
    quad(
      blankNodes[25],
      namedNode(`${sh}path`),
      namedNode(`${ns1}name`)
    ),
    quad(
      blankNodes[25],
      namedNode(`${sh}name`),
      literal(`name`)
    ),
    quad(
      blankNodes[25],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[25],
      namedNode(`${sh}minCount`),
      literal(`0`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMMappingPropertyShape`),
      namedNode(`${sh}property`),
      blankNodes[25]
    ),
    quad(
      blankNodes[26],
      namedNode(`${sh}path`),
      namedNode(`${ns1}description`)
    ),
    quad(
      blankNodes[26],
      namedNode(`${sh}name`),
      literal(`description`)
    ),
    quad(
      blankNodes[26],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[26],
      namedNode(`${sh}minCount`),
      literal(`0`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMMappingPropertyShape`),
      namedNode(`${sh}property`),
      blankNodes[26]
    ),
    quad(
      blankNodes[27],
      namedNode(`${sh}path`),
      namedNode(`${sh}path`)
    ),
    quad(
      blankNodes[27],
      namedNode(`${sh}name`),
      literal(`path`)
    ),
    quad(
      blankNodes[27],
      namedNode(`${sh}datatype`),
      namedNode(`${xsd}string`)
    ),
    quad(
      blankNodes[27],
      namedNode(`${sh}minCount`),
      literal(`0`, namedNode(`${xsd}integer`))
    ),
    quad(
      namedNode(`${ns1}XRMMappingPropertyShape`),
      namedNode(`${sh}property`),
      blankNodes[27]
    ),

  ]
}
